# 设置是否启用插件
enabled: true
# 设置TPS检测间隔，单位(ms)
interval: 1000
# 设置最低TPS限值
tpslimit: 14.0
# 设置执行命令前的倒计时提示语，%d变量表示倒计时时间，单位(s)
message: "TPS< 14.0，服务器将在%d秒后重启"
# 设置倒计时完成后要执行的指令
commands:
- 'save-all'
- 'stop'
# 设置倒计时提示信息的时间，单位(s)
downcount:
- 20
- 10
- 9
- 8
- 7
- 6
- 5
- 4
- 3
- 2
- 1
